export const ticketData = [
    {
      id: "TK-001",
      title: "Sistema de login não funciona corretamente",
      description: "Ao tentar fazer login, o sistema apresenta erro após inserir as credenciais corretas.",
      type: "bug",
      status: "open",
      priority: "high",
      createdAt: "2023-10-15",
      createdBy: "João Silva",
      department: "TI",
    },
    {
      id: "TK-002",
      title: "Sugestão de melhoria para o dashboard",
      description: "Seria útil ter gráficos de desempenho no dashboard principal para visualizar métricas importantes.",
      type: "feature",
      status: "in-progress",
      priority: "medium",
      createdAt: "2023-10-14",
      createdBy: "Maria Oliveira",
      department: "Marketing",
    },
    {
      id: "TK-003",
      title: "Problema com geração de relatórios",
      description: "Os relatórios mensais estão sendo gerados com dados incompletos.",
      type: "bug",
      status: "resolved",
      priority: "high",
      createdAt: "2023-10-10",
      createdBy: "Carlos Santos",
      department: "Financeiro",
    },
    {
      id: "TK-004",
      title: "Reclamação sobre ambiente de trabalho",
      description: "O ar condicionado da sala 302 não está funcionando adequadamente há uma semana.",
      type: "complaint",
      status: "in-progress",
      priority: "medium",
      createdAt: "2023-10-08",
      createdBy: "Ana Pereira",
      department: "RH",
    },
    {
      id: "TK-005",
      title: "Solicitação de novo equipamento",
      description: "Necessito de um segundo monitor para melhorar a produtividade no desenvolvimento.",
      type: "support",
      status: "open",
      priority: "low",
      createdAt: "2023-10-05",
      createdBy: "Pedro Costa",
      department: "TI",
    },
    {
      id: "TK-006",
      title: "Erro crítico no sistema de pagamentos",
      description: "O sistema de pagamentos está calculando incorretamente os valores dos salários.",
      type: "bug",
      status: "open",
      priority: "critical",
      createdAt: "2023-10-03",
      createdBy: "Fernanda Lima",
      department: "Financeiro",
    },
    {
      id: "TK-007",
      title: "Sugestão para melhorar processo de onboarding",
      description:
        "Podemos criar um checklist digital para novos funcionários seguirem durante o processo de integração.",
      type: "feature",
      status: "closed",
      priority: "medium",
      createdAt: "2023-09-28",
      createdBy: "Roberto Alves",
      department: "RH",
    },
    {
      id: "TK-008",
      title: "Problema com acesso ao sistema de arquivos",
      description: "Não consigo acessar a pasta compartilhada do departamento desde ontem.",
      type: "support",
      status: "resolved",
      priority: "high",
      createdAt: "2023-09-25",
      createdBy: "Juliana Martins",
      department: "Marketing",
    },
    {
      id: "TK-009",
      title: "Reclamação sobre barulho excessivo",
      description: "A equipe do andar de cima está fazendo muito barulho durante as reuniões.",
      type: "complaint",
      status: "open",
      priority: "low",
      createdAt: "2023-09-22",
      createdBy: "Marcelo Souza",
      department: "Operações",
    },
    {
      id: "TK-010",
      title: "Sugestão de ferramenta para gerenciamento de projetos",
      description: "Podemos adotar o Trello para melhorar a organização e acompanhamento dos projetos da equipe.",
      type: "feature",
      status: "in-progress",
      priority: "medium",
      createdAt: "2023-09-20",
      createdBy: "Camila Rocha",
      department: "TI",
    },
  ]
  
  